/* generated by stasc 1.5 */
gui = {};

gui.folder_container=function(){
	var n0=document.createElement('div');
	var n1=document.createElement('div');
	n1.setAttribute('class','title-bar');
	Object.defineProperty(n0,'$drag',{
		get:function(){return n1;}
	});
	var n2=document.createElement('span');
	n2.setAttribute('style','position:absolute; left:5px; cursor:move;');
	var n3=document.createElement('img');
	n3.setAttribute('src','folder.png');
	n3.setAttribute('align','left');
	n3.setAttribute('style','opacity:0.5;');
	n2.appendChild(n3);
	var n4=document.createElement('span');
	n4.setAttribute('style','color:white; font-weight:bold;');
	Object.defineProperty(n0, '$title',{
		set:function(v){n4.textContent=v;},
		get:function(){return n4.textContent;}
	});
	n2.appendChild(n4);
	n1.appendChild(n2);
	var n5=document.createElement('span');
	n5.setAttribute('style','position:absolute; right:5px; cursor:pointer;');
	var n6=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n6.setAttribute('width','24');
	n6.setAttribute('height','24');
	n6.setAttribute('style','opacity:0.5;');
	n6.setAttribute('title','Reload');
	var n7=document.createElementNS('http://www.w3.org/2000/svg','g');
	Object.defineProperty(n0,'$reloadIcon',{
		set:function(v){n6.replaceChild(v,n7);n7=v;},
		get:function(){return n7;}
	});
	n6.appendChild(n7);
	Object.defineProperty(n0,'$reload',{
		get:function(){return n6;}
	});
	n5.appendChild(n6);
	var n8=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n8.setAttribute('width','24');
	n8.setAttribute('height','24');
	n8.setAttribute('style','opacity:0.5;');
	n8.setAttribute('title','Close');
	var n9=document.createElementNS('http://www.w3.org/2000/svg','line');
	n9.setAttribute('x1','4');
	n9.setAttribute('y1','4');
	n9.setAttribute('x2','20');
	n9.setAttribute('y2','20');
	n9.setAttribute('stroke','black');
	n9.setAttribute('stroke-width','5');
	n8.appendChild(n9);
	var n10=document.createElementNS('http://www.w3.org/2000/svg','line');
	n10.setAttribute('x1','20');
	n10.setAttribute('y1','4');
	n10.setAttribute('x2','4');
	n10.setAttribute('y2','20');
	n10.setAttribute('stroke','black');
	n10.setAttribute('stroke-width','5');
	n8.appendChild(n10);
	Object.defineProperty(n0,'$close',{
		get:function(){return n8;}
	});
	n5.appendChild(n8);
	n1.appendChild(n5);
	n0.appendChild(n1);
	var n11=document.createElement('div');
	n11.setAttribute('style','padding:2px; border:solid 1px; overflow:scroll; position:absolute; left:0px; right:0px; top:35px; bottom:0px;');
	var n12=document.createElement('table');
	n12.setAttribute('style','width:100%; border-spacing:0px; empty-cells:show;');
	Object.defineProperty(n0,'$content',{
		set:function(v){n11.replaceChild(v,n12);n12=v;},
		get:function(){return n12;}
	});
	n11.appendChild(n12);
	n0.appendChild(n11);
	var n13=document.createElement('div');
	n13.setAttribute('style','position:absolute; width:1em; height:1em; right:0px; bottom:0px; cursor:se-resize; background-color:white; opacity:0;');
	Object.defineProperty(n0,'$resize',{
		get:function(){return n13;}
	});
	n0.appendChild(n13);
	return n0;
};
gui.item1=function(){
	var n0=document.createElement('tr');
	var n1=document.createElement('td');
	n1.setAttribute('style','border-bottom:1px solid lightgray; padding:0px; margin:0px;');
	var n2=document.createElement('span');
	n2.setAttribute('draggable','true');
	n2.setAttribute('style','cursor:pointer;');
	var n3=document.createElement('img');
	n3.setAttribute('align','left');
	n3.setAttribute('draggable','false');
	n3.setAttribute('style','opacity:0.5;');
	Object.defineProperty(n0, '$icon',{
		set:function(v){n3.src=v;},
		get:function(){return n3.src;}
	});
	n2.appendChild(n3);
	var n4=document.createElement('span');
	Object.defineProperty(n0, '$name',{
		set:function(v){n4.textContent=v;},
		get:function(){return n4.textContent;}
	});
	n2.appendChild(n4);
	n1.appendChild(n2);
	var n5=document.createElement('a');
	n5.setAttribute('target','_blank');
	n5.setAttribute('draggable','false');
	Object.defineProperty(n0, '$url',{
		set:function(v){n5.href=v;},
		get:function(){return n5.href;}
	});
	var n6=document.createElement('img');
	n6.setAttribute('align','top');
	n6.setAttribute('src','link.png');
	n6.setAttribute('draggable','false');
	n6.setAttribute('style','opacity:0.5;');
	n5.appendChild(n6);
	n1.appendChild(n5);
	n0.appendChild(n1);
	var n7=document.createElement('td');
	n7.setAttribute('align','center');
	n7.setAttribute('style','border-bottom:1px solid lightgray; padding:0px; margin:0px;');
	Object.defineProperty(n0, '$time',{
		set:function(v){n7.textContent=v;},
		get:function(){return n7.textContent;}
	});
	n0.appendChild(n7);
	var n8=document.createElement('td');
	n8.setAttribute('align','right');
	n8.setAttribute('style','border-bottom:1px solid lightgray; padding:0px; margin:0px;');
	Object.defineProperty(n0, '$size',{
		set:function(v){n8.textContent=v;},
		get:function(){return n8.textContent;}
	});
	n0.appendChild(n8);
	return n0;
};
gui.list1=function(){
	var n0=document.createElement('table');
	n0.setAttribute('style','width:100%; border-spacing:0px; empty-cells:show;');
	var n1=document.createElement('tbody');
	Object.defineProperty(n0,'$items',{
		get:function(){return n1;}
	});
	n0.appendChild(n1);
	return n0;
};
gui.name=function(){
	var n0=document.createElement('div');
	n0.setAttribute('style','position:absolute; left:0; right:0; top:0; bottom:0;');
	var n1=document.createElement('div');
	n1.setAttribute('style','position:absolute; left:0; right:0; top:0; bottom:0; background-color:gray; opacity:0.5;');
	n0.appendChild(n1);
	var n2=document.createElement('div');
	n2.setAttribute('style','position:absolute; left:0; right:0; top:0; bottom:0;');
	var n3=document.createElement('div');
	n3.setAttribute('style','margin-top:30%; margin-left:auto; margin-right:auto; padding: 5px; width:300px; background-color:white; border:1px solid; border-radius: 5px;');
	var n4=document.createElement('img');
	n4.setAttribute('src','folder.png');
	n4.setAttribute('align','center');
	n4.setAttribute('style','opacity:0.5;');
	n3.appendChild(n4);
	var n5=document.createElement('span');
	Object.defineProperty(n0, '$message',{
		set:function(v){n5.textContent=v;},
		get:function(){return n5.textContent;}
	});
	if(0<arguments.length){
		n0.$message=arguments[0];
	}
	n3.appendChild(n5);
	var n6=document.createElement('input');
	n6.setAttribute('type','text');
	Object.defineProperty(n0,'$input',{
		get:function(){return n6;}
	});
	Object.defineProperty(n0, '$text',{
		set:function(v){n6.value=v;},
		get:function(){return n6.value;}
	});
	n3.appendChild(n6);
	var n7=document.createElement('div');
	n7.setAttribute('style','text-align:right;');
	var n8=document.createElement('input');
	n8.setAttribute('type','button');
	n8.setAttribute('value','OK');
	Object.defineProperty(n0,'$ok',{
		get:function(){return n8;}
	});
	n7.appendChild(n8);
	n3.appendChild(n7);
	n2.appendChild(n3);
	n0.appendChild(n2);
	return n0;
};
gui.reload_busy=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	n0.setAttribute('transform','rotate(0 12 12)');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','animateTransform');
	n1.setAttribute('attributeName','transform');
	n1.setAttribute('type','rotate');
	n1.setAttribute('from','0 12 12');
	n1.setAttribute('to','180 12 12');
	n1.setAttribute('dur','1s');
	n1.setAttribute('repeatCount','indefinite');
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','path');
	n2.setAttribute('d','M 12 20 A 8 8 0 0 1 6.343 6.343');
	n2.setAttribute('stroke','black');
	n2.setAttribute('stroke-width','5');
	n2.setAttribute('fill','none');
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','polyline');
	n3.setAttribute('points','3,3 10,10 10,3');
	n3.setAttribute('stroke','none');
	n3.setAttribute('fill','black');
	n0.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','path');
	n4.setAttribute('d','M 12 4 A 8 8 0 0 1 17.657 17.657');
	n4.setAttribute('stroke','black');
	n4.setAttribute('stroke-width','5');
	n4.setAttribute('fill','none');
	n0.appendChild(n4);
	var n5=document.createElementNS('http://www.w3.org/2000/svg','polyline');
	n5.setAttribute('points','21,21 14,14 14,21');
	n5.setAttribute('stroke','none');
	n5.setAttribute('fill','black');
	n0.appendChild(n5);
	return n0;
};
gui.reload_ready=function(){
	var n0=document.createElementNS('http://www.w3.org/2000/svg','g');
	var n1=document.createElementNS('http://www.w3.org/2000/svg','path');
	n1.setAttribute('d','M 12 20 A 8 8 0 0 1 6.343 6.343');
	n1.setAttribute('stroke','black');
	n1.setAttribute('stroke-width','5');
	n1.setAttribute('fill','none');
	n0.appendChild(n1);
	var n2=document.createElementNS('http://www.w3.org/2000/svg','polyline');
	n2.setAttribute('points','3,3 10,10 10,3');
	n2.setAttribute('stroke','none');
	n2.setAttribute('fill','black');
	n0.appendChild(n2);
	var n3=document.createElementNS('http://www.w3.org/2000/svg','path');
	n3.setAttribute('d','M 12 4 A 8 8 0 0 1 17.657 17.657');
	n3.setAttribute('stroke','black');
	n3.setAttribute('stroke-width','5');
	n3.setAttribute('fill','none');
	n0.appendChild(n3);
	var n4=document.createElementNS('http://www.w3.org/2000/svg','polyline');
	n4.setAttribute('points','21,21 14,14 14,21');
	n4.setAttribute('stroke','none');
	n4.setAttribute('fill','black');
	n0.appendChild(n4);
	return n0;
};
gui.text_container=function(){
	var n0=document.createElement('div');
	var n1=document.createElement('div');
	n1.setAttribute('class','title-bar');
	Object.defineProperty(n0,'$drag',{
		get:function(){return n1;}
	});
	var n2=document.createElement('span');
	n2.setAttribute('style','position:absolute; left:5px; cursor:move;');
	var n3=document.createElement('img');
	n3.setAttribute('src','text.png');
	n3.setAttribute('align','left');
	n3.setAttribute('style','opacity:0.5;');
	n2.appendChild(n3);
	var n4=document.createElement('span');
	n4.setAttribute('style','color:white; font-weight:bold;');
	Object.defineProperty(n0, '$title',{
		set:function(v){n4.textContent=v;},
		get:function(){return n4.textContent;}
	});
	n2.appendChild(n4);
	n1.appendChild(n2);
	var n5=document.createElement('span');
	n5.setAttribute('style','position:absolute; right:5px; cursor:pointer;');
	var n6=document.createElement('img');
	n6.setAttribute('src','upload.png');
	n6.setAttribute('style','opacity:0.2;');
	n6.setAttribute('title','Upload');
	Object.defineProperty(n0,'$upload',{
		get:function(){return n6;}
	});
	Object.defineProperty(n0, '$uploadIcon',{
		set:function(v){n6.src=v;},
		get:function(){return n6.src;}
	});
	n5.appendChild(n6);
	var n7=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n7.setAttribute('width','24');
	n7.setAttribute('height','24');
	n7.setAttribute('style','opacity:0.5;');
	n7.setAttribute('title','Reload');
	var n8=document.createElementNS('http://www.w3.org/2000/svg','g');
	Object.defineProperty(n0,'$reloadIcon',{
		set:function(v){n7.replaceChild(v,n8);n8=v;},
		get:function(){return n8;}
	});
	n7.appendChild(n8);
	Object.defineProperty(n0,'$reload',{
		get:function(){return n7;}
	});
	n5.appendChild(n7);
	var n9=document.createElementNS('http://www.w3.org/2000/svg','svg');
	n9.setAttribute('width','24');
	n9.setAttribute('height','24');
	n9.setAttribute('style','opacity:0.5;');
	n9.setAttribute('title','Close');
	var n10=document.createElementNS('http://www.w3.org/2000/svg','line');
	n10.setAttribute('x1','4');
	n10.setAttribute('y1','4');
	n10.setAttribute('x2','20');
	n10.setAttribute('y2','20');
	n10.setAttribute('stroke','black');
	n10.setAttribute('stroke-width','5');
	n9.appendChild(n10);
	var n11=document.createElementNS('http://www.w3.org/2000/svg','line');
	n11.setAttribute('x1','20');
	n11.setAttribute('y1','4');
	n11.setAttribute('x2','4');
	n11.setAttribute('y2','20');
	n11.setAttribute('stroke','black');
	n11.setAttribute('stroke-width','5');
	n9.appendChild(n11);
	Object.defineProperty(n0,'$close',{
		get:function(){return n9;}
	});
	n5.appendChild(n9);
	n1.appendChild(n5);
	n0.appendChild(n1);
	var n12=document.createElement('div');
	n12.setAttribute('style','margin:0px; padding:0px; border:solid 1px; position:absolute; left:0px; right:0px; top:35px; bottom:0px;');
	var n13=document.createElement('textarea');
	n13.setAttribute('style','margin:0px; padding:0px; border:0px; width:100%; height:100%; resize:none;');
	Object.defineProperty(n0,'$textarea',{
		get:function(){return n13;}
	});
	Object.defineProperty(n0, '$text',{
		set:function(v){n13.value=v;},
		get:function(){return n13.value;}
	});
	n12.appendChild(n13);
	n0.appendChild(n12);
	var n14=document.createElement('div');
	n14.setAttribute('style','position:absolute; width:1em; height:1em; right:0px; bottom:0px; cursor:se-resize;');
	Object.defineProperty(n0,'$resize',{
		get:function(){return n14;}
	});
	n0.appendChild(n14);
	return n0;
};
